services:
  - type: web
    name: p2-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    branch: develop
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    buildFilter:
      paths:
        - package.json
        - Dockerfile
        - src/** 